import { Source, SourceClass, Platform, TranscriptSegment } from '@yanghoo/domain';
import { nanoid } from 'nanoid';
import { execSync } from 'child_process';
import * as fs from 'fs';

export interface RawYouTubeMetadata {
  id: string;
  title: string;
  author: string;
  duration: number;
  thumbnailUrl: string;
  url: string;
}

export interface FetchTranscriptResult {
  segments: TranscriptSegment[];
  language?: string;
  trackName?: string;
}

export class YouTubeSourceAdapter {
  /**
   * Captures metadata from a YouTube URL.
   * For MVP: This uses a simplified logic or mock if no library is ready.
   */
  async capture(url: string): Promise<Source> {
    // Extract video ID from URL
    const videoIdMatch = url.match(/(?:v=|\/be\/|embed\/|v\/|shorts\/)([^#&?]*)/);
    const videoId = videoIdMatch ? videoIdMatch[1] : nanoid();

    console.log(`[YouTubeAdapter] Capturing URL: ${url} (Video ID: ${videoId})`);

    // Mocking metadata fetch for now
    const mockMetadata: RawYouTubeMetadata = {
      id: videoId,
      title: `YouTube Video ${videoId}`,
      author: 'Unknown Creator',
      duration: 0,
      thumbnailUrl: `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
      url
    };

    return {
      id: `yt-${videoId}`,
      sourceClass: 'long_video',
      platform: 'youtube',
      url: mockMetadata.url,
      title: mockMetadata.title,
      author: mockMetadata.author,
      thumbnailUrl: mockMetadata.thumbnailUrl,
      duration: mockMetadata.duration,
      capturedAt: new Date().toISOString(),
      metadata: {
        videoId: mockMetadata.id
      }
    };
  }

  /**
   * Fetches real transcript segments for a given video ID using yt-dlp.
   */
  async fetchTranscript(videoId: string): Promise<FetchTranscriptResult> {
    console.log(`[YouTubeAdapter] Fetching real transcript for video: ${videoId} using yt-dlp`);
    
    const tempPrefix = `temp_transcript_${nanoid()}`;
    const url = `https://www.youtube.com/watch?v=${videoId}`;
    
    try {
      // Try to fetch manual subs first, then auto-subs
      // Use --ignore-errors to continue if some languages fail (e.g. 429 Too Many Requests on some tracks)
      const cmd = `yt-dlp --write-subs --write-auto-subs --skip-download --sub-langs "en.*,zh.*" --sub-format json3 --ignore-errors --output "${tempPrefix}" "${url}"`;
      console.log(`[YouTubeAdapter] Running: ${cmd}`);
      execSync(cmd, { stdio: 'inherit' });
      
      // Find the generated file. It will be tempPrefix.lang.json3
      const files = fs.readdirSync('.').filter(f => f.startsWith(tempPrefix) && f.endsWith('.json3'));
      
      if (files.length === 0) {
        throw new Error(`No transcript files generated by yt-dlp for video: ${videoId}`);
      }
      
      const transcriptFile = files[0];
      const langMatch = transcriptFile.match(new RegExp(`${tempPrefix}\\.(.*?)\\.json3`));
      const language = langMatch ? langMatch[1] : undefined;
      
      console.log(`[YouTubeAdapter] Loading transcript from ${transcriptFile} (language: ${language})`);
      const transcriptData = JSON.parse(fs.readFileSync(transcriptFile, 'utf-8'));
      
      // Cleanup
      files.forEach(f => fs.unlinkSync(f));
      
      if (!transcriptData.events) {
        throw new Error(`Invalid transcript data format for video: ${videoId}`);
      }
      
      const segments: TranscriptSegment[] = transcriptData.events
        .filter((event: any) => event.segs)
        .map((event: any) => {
          const text = event.segs.map((seg: any) => seg.utf8).join('').trim();
          const start = event.tStartMs / 1000;
          const duration = (event.dDurationMs || 0) / 1000;
          return {
            text,
            start,
            end: start + duration
          };
        });
        
      if (segments.length === 0) {
        throw new Error(`Fetched transcript has 0 segments for video: ${videoId}`);
      }

      return {
        segments,
        language,
        trackName: 'yt-dlp fetched track'
      };
    } catch (error: any) {
      console.error(`[YouTubeAdapter] Error fetching transcript: ${error.message}`);
      // Ensure cleanup on error
      try {
        const files = fs.readdirSync('.').filter(f => f.startsWith(tempPrefix));
        files.forEach(f => fs.unlinkSync(f));
      } catch (e) {}
      throw error;
    }
  }
}

export const youtubeAdapter = new YouTubeSourceAdapter();
